### ISSUE TITLE
Research parser generator

### ISSUE THREAD

**Issue by jkurdek** [Kurdeks/jbcc#3]
Do initial research on parser generators. Look at https://www.gnu.org/software/bison/

**Comment by Willu12** [comment]
Parsing with bison:
- it's simply addable with cmake
- we have to create parse.y file in bison syntax
- we can use already existing parse.y files (https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/c-parse.in;h=66d27ac0322f335aed8a3302522bcf19ffc9d1bf;hb=359e576cf4a70392fda974114498ba451310ab05)

**Comment by Willu12** [comment]
# useful link
https://www.progtools.org/compilers/tutorials/cxx_and_bison/cxx_and_bison.html

**Comment by jkurdek** [comment]
Using existing parse.y could be a good idea. With the once you posted we do not need to use separate lexer as bison will do the job of the both of them. 

Alternatively we can use both flex and bison. Those two should do the job:
https://www.quut.com/c/ANSI-C-grammar-y-2011.html
https://www.quut.com/c/ANSI-C-grammar-l-2011.html
